# Production Docker Compose for idudesRAG
version: '3.8'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: idudes-rag-ui
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # DigitalOcean Spaces
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_REGION=${SPACES_REGION}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
      - SPACES_CDN_URL=${SPACES_CDN_URL}
      
      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # n8n Webhooks
      - NEXT_PUBLIC_N8N_URL=${NEXT_PUBLIC_N8N_URL}
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      
      # Next.js
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    
    env_file:
      - .env
    
    networks:
      - idudes-network
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/test-env"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  idudes-network:
    driver: bridge