networks:
  3e-network:
    external: true

services:
  # Document Processing Service - SIMPLIFIED
  doc-processor:
    container_name: idudes-doc-processor
    image: node:20-alpine
    restart: unless-stopped
    networks:
      - 3e-network
    volumes:
      - ./processor:/app
      - ./documents:/documents
      - ./processed:/processed
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
      - SPACES_BUCKET=${SPACES_BUCKET}
      - SPACES_REGION=${SPACES_REGION}
      - SPACES_ENDPOINT=${SPACES_ENDPOINT}
    working_dir: /app
    command: npm start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.idudes-processor.rule=Host(`docs.thirdeyediagnostics.com`)"
      - "traefik.http.routers.idudes-processor.tls=true"
      - "traefik.http.routers.idudes-processor.tls.certresolver=acmehttp"
      - "traefik.http.services.idudes-processor.loadbalancer.server.port=3000"

# NO MINIO - Using DigitalOcean Spaces
# NO REDIS - Not needed for document processing
# NO POSTGRESQL - Using Railway pgvector
